---
title:  "Synonymous vs nonsynonymous SNPs in Mito genome"
author: "Natalia Zajac"
output:
  html_document: 
  highlight: pygments
  theme: sand
  code_folding: hide
  toc: yes
  toc_depth: 4
  editor_options: 
  chunk_output_type: inline
---

Started on `r format(Sys.time(), "%Y-%m-%d %H:%M:%S")`


```{r setup, include=FALSE}
library(poolfstat)
library(pheatmap)
library(dplyr)
library(cowplot)
library(patchwork)
library(readr)
library(stringr)
library(tidyverse)
library(textshaping)
library(ggpubr)
library(ggrepel)

working_dir=getwd()
source(paste0(working_dir,"/../BayPass/baypass_utils.R"))

df = read_delim(paste0(working_dir,"/../test.sync")) # just for colnames
poolnames = str_remove(sapply(str_split(colnames(df)[c(-1:-3)], "\\."), .subset, 2), "B-")

pooldatamt = popsync2pooldata(
    sync.file = paste0(working_dir,"/../all_samples.mit.sync.filtered.sync"),
    poolsizes = c(rep(24,15)),
    poolnames = poolnames[-13],
    noindel = TRUE,
    nlines.per.readblock = 1e+06,
    nthreads = 1, min.maf = 0.0001
)
mtcov= data.frame(pooldatamt@readcoverage)
mtcov = cbind(data.frame(pooldatamt@snp.info), mtcov)
tokeep = mtcov %>%
    filter(if_all(5:19, ~ . < 6000))
pooldatamt = poolfstat::pooldata.subset(pooldatamt, snp.index = as.numeric(rownames(tokeep)))
mito = (data.frame(pooldatamt@refallele.readcount)* 100)/data.frame(pooldatamt@readcoverage)
colnames(mito) = pooldatamt@poolnames
mito = cbind(data.frame(pooldatamt@snp.info), mito)
to_filter = rownames(mito[rowSums(mito[, 5:19] >= 95) == 15 | rowSums(mito[, 5:19] <= 5) == 15, ])
mito = mito[!rownames(mito) %in% to_filter,]

# Select SNPs divergent between M and W/CA hapltoypes and save them for functional annotation in snpeff
Mhap_SNPs = mito[rowSums(mito[,c(5:7, 11:13)] < 5) == 6 & rowSums(mito[,c(8:10, 14:19)] >= 95) == 9, c(1,2,3,4)]
write_delim(Mhap_SNPs, "/Users/nataliazajac/snpEff/Mhap/mt.Mhap.bed", delim = "\t")

Whap_CAhap_SNPs = mito[rowSums(mito[,c(5:7, 11:13)] >= 95) == 6 & rowSums(mito[,c(8:10, 14:19)] < 5) == 9, c(1,2,3,4)]
write_delim(Whap_CAhap_SNPs, "/Users/nataliazajac/snpEff/WCAhap/mt.WhapCAhap.bed", delim = "\t")

#in snpeff folder 
#python $working_dir/SnpEff/variants_to_vcf.py /Users/nataliazajac/snpEff/Mhap/mt.Mhap.bed /Users/nataliazajac/snpEff/Mhap/mt.Mhap.vcf
#java -Xmx4g -jar snpEff.jar ann -v ASM1340708v1_Mito /Users/nataliazajac/snpEff/Mhap/mt.Mhap.vcf > /Users/nataliazajac/snpEff/Mhap/mt.Mhapannot.vcf
#python $working_dir/SnpEff/variants_to_vcf.py /Users/nataliazajac/snpEff/WCAhap/mt.WhapCAhap.bed /Users/nataliazajac/snpEff/WCAhap/mt.WhapCAhap.vcf
#java -Xmx4g -jar snpEff.jar ann -v ASM1340708v1_Mito /Users/nataliazajac/snpEff/WCAhap/mt.WhapCAhap.vcf > /Users/nataliazajac/snpEff/WCAhap/mt.WhapCAhapannot.vcf

Mhap = read.vcfR("/Users/nataliazajac/snpEff/Mhap/mt.Mhapannot.vcf")
Mhap = data.frame(effect = sapply(str_split(data.frame(Mhap@fix)$INFO, "\\|"), .subset, 2), gene = sapply(str_split(data.frame(Mhap@fix)$INFO, "\\|"), .subset, 4))
WCAhap = read.vcfR("/Users/nataliazajac/snpEff/WCAhap/mt.WhapCAhapannot.vcf")
WCAhap = data.frame(effect = sapply(str_split(data.frame(WCAhap@fix)$INFO, "\\|"), .subset, 2), gene = sapply(str_split(data.frame(WCAhap@fix)$INFO, "\\|"), .subset, 4))

```

## Figure 4G

```{r setup, include=FALSE}
pdf(paste0(working_dir,"/../Figures/MitoGenesVariants.pdf"), height = 5, width = 9)
rbind(Mhap, WCAhap) %>% group_by(gene, effect) %>% summarise(count = n()) %>% mutate(effect = str_replace(str_replace(effect, "_", " "), "_", " "))  %>% mutate(effect = str_replace(str_replace(effect, "&", " & "), "_", " ")) %>% 
    ggplot(aes(count, toupper(gene), fill = effect)) +
    geom_col(position = position_dodge2(width = 0.9, preserve = "single")) +
    labs(y = "Gene Name", x="Number of SNPs", fill = "Annotation") +
    ggtitle("MT variants between M and W/CA haplotypes") +
    theme(title = element_text(size = 15),
        axis.title.x = element_text(size = 15),
        axis.text.x = element_text(size = 15),
        axis.title.y = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.position = c(0.8, 0.5),
        legend.background = element_rect(fill = "white", colour = "black")
    ) +
    scale_x_sqrt() +
    scale_fill_manual(
        values = c("chartreuse","dodgerblue4","dodgerblue","deeppink4"),
        labels = function(x) stringr::str_wrap(x, width = 30)
    )
dev.off()
```
